language: r
cache: packages
r:
    - release

sudo: false

addons:
      apt:
          packages:
              - libgsl0-dev
                        
before_install:
    - #

script:
    - cd travisTest
    - printf "starting run\n"
    - Rscript test.R
